# Generated by Django 3.0.6 on 2021-03-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesort', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
                ('nickname', models.CharField(db_index=True, max_length=20, verbose_name='匿名')),
                ('typename', models.CharField(db_index=True, max_length=20, verbose_name='类别')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['typesort'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(default='', verbose_name='正文')),
                ('attachmt', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件')),
                ('parentid', models.IntegerField(db_index=True, default=0, verbose_name='父评')),
                ('commfoor', models.IntegerField(db_index=True, default=1, verbose_name='楼层')),
                ('likenumb', models.IntegerField(db_index=True, default=0, verbose_name='喜欢')),
                ('niminswh', models.BooleanField(default=False, verbose_name='匿名')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-creatime'],
            },
        ),
        migrations.CreateModel(
            name='Mtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesort', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
                ('typename', models.CharField(db_index=True, max_length=20, verbose_name='名称')),
                ('nickname', models.CharField(db_index=True, max_length=20, verbose_name='匿名')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('typelogo', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
            ],
            options={
                'verbose_name': '商类',
                'verbose_name_plural': '商类',
                'ordering': ['typesort'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endptime', models.CharField(default=0, max_length=128, verbose_name='最后')),
                ('profsite', models.CharField(max_length=255, null=True, verbose_name='主页')),
                ('usravatr', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('whatdoth', models.CharField(max_length=255, null=True, verbose_name='此刻')),
                ('usersage', models.CharField(max_length=255, null=True, verbose_name='年龄')),
                ('userback', models.CharField(max_length=255, null=True, verbose_name='封面')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('niminswh', models.BooleanField(default=False, verbose_name='匿名')),
                ('backswih', models.BooleanField(default=False, verbose_name='封面')),
                ('location', models.TextField(null=True, verbose_name='位置')),
                ('pointnum', models.IntegerField(db_index=True, default=0, verbose_name='积分')),
                ('usrgrade', models.IntegerField(db_index=True, default=0, verbose_name='等级')),
                ('recvmail', models.BooleanField(db_index=True, default=False, verbose_name='接收')),
                ('activeml', models.BooleanField(db_index=True, default=False, verbose_name='激活')),
                ('uaddress', models.GenericIPAddressField(db_index=True, null=True, verbose_name='地址')),
                ('usermail', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='邮箱')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('urgender', models.CharField(blank=True, max_length=255, null=True, verbose_name='性别')),
                ('nickname', models.CharField(max_length=128, null=True, unique=True, verbose_name='编号')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-creatime'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='正文')),
                ('attachmt', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件')),
                ('videourl', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频')),
                ('commnumb', models.IntegerField(db_index=True, default=0, verbose_name='评论')),
                ('likenumb', models.IntegerField(db_index=True, default=0, verbose_name='喜欢')),
                ('niminswh', models.BooleanField(default=False, verbose_name='匿名')),
                ('updatime', models.DateTimeField(auto_now=True, verbose_name='更新')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('thauthor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='作者')),
                ('thontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category',
                                               verbose_name='类别')),
            ],
            options={
                'verbose_name': '线程',
                'verbose_name_plural': '线程',
                'ordering': ['-updatime'],
            },
        ),
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointnum', models.IntegerField(db_index=True, default=0, verbose_name='点数')),
                ('pointlat', models.IntegerField(db_index=True, default=0, verbose_name='余额')),
                ('pointtyp', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='类型')),
                ('pointdes', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='描述')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('pointusr',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分',
                'verbose_name_plural': '积分',
                'ordering': ['-creatime'],
            },
        ),
        migrations.CreateModel(
            name='NotifySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replymys', models.CharField(db_index=True, max_length=128, verbose_name='我的')),
                ('isreaded', models.BooleanField(db_index=True, default=False, verbose_name='已读')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('replycom',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Comment', verbose_name='评论')),
                ('replyhes',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='他的')),
                ('replythd',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Thread', verbose_name='线程')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-creatime'],
            },
        ),
        migrations.CreateModel(
            name='MThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='描述')),
                ('hidecont', models.TextField(blank=True, null=True, verbose_name='隐藏')),
                ('howmanyp', models.IntegerField(db_index=True, default=0, verbose_name='人数')),
                ('mktprice', models.IntegerField(db_index=True, default=0, verbose_name='价格')),
                ('mktstock', models.IntegerField(db_index=True, default=0, verbose_name='库存')),
                ('mketname', models.CharField(db_index=True, max_length=255, verbose_name='名称')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('mketchat', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系')),
                ('attachmt', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件')),
                ('mkettype',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Mtype', verbose_name='商类')),
                ('postuser',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-creatime'],
            },
        ),
        migrations.CreateModel(
            name='GoodSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('goodcomm',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Comment',
                                   verbose_name='评论')),
                ('goodthed',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Thread',
                                   verbose_name='线程')),
                ('gooduser',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'ordering': ['-creatime'],
            },
        ),
        migrations.CreateModel(
            name='EmailActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('activecd', models.CharField(max_length=255, verbose_name='代码')),
                ('endptime', models.CharField(default=0, max_length=128, verbose_name='最后')),
                ('mailuser',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '激活',
                'verbose_name_plural': '激活',
                'ordering': ['-creatime'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='cmauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmthread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Thread', verbose_name='线程'),
        ),
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaddress', models.GenericIPAddressField(verbose_name='地址')),
                ('bkreason', models.CharField(max_length=255, null=True, verbose_name='理由')),
                ('endptime', models.DateTimeField(verbose_name='结束')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('fuckuser',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.User',
                                   verbose_name='用户')),
            ],
            options={
                'verbose_name': '黑单',
                'verbose_name_plural': '黑单',
                'ordering': ['-creatime'],
            },
        ),
    ]
